### ISSUE TITLE
Constants를 enum으로 분리하는 것이 어떨까요?

### ISSUE THREAD

**Issue by SeRDic0705** [NBC-SRPG/SRPG#24]
현재 Constants 클래스 내에서 상수와 열거형을 구분하지 않고 사용하고 있습니다.

아예 Const와 Enum을 분리해서 클래스가 아닌 namespace로 사용하는 것이 좋아보이는데

현재 develop브랜치 외에 enum을 새로 추가하여 작업 중인 브랜치가 있을까요?

충돌우려 때문에 작업전에 미리 확인하려합니다

#SRPG-64

**Comment by chai227chai** [comment]
지금 constants에 enum을 더 추가하는 중이라 모든 작업의 merge가 끝나고 한번에 진행하는게 좋을 것 같습니다
